iotivity-sensorboard: Use regular LDFLAGS variable and pthread
Without this change and error on linkage is displayed :

  ld: observer.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
  libpthread.so.0: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status

Also YOCTOLDFLAGS are replaced with regular LDFLAGS,
 to use quality check.

Without this, QA check is failing and this message is reported:

  do_package_qa: QA Issue: No GNU_HASH in the elf binary:

Change-Id: I80e4ab17128b8539a45843611e4aec3650e2ddef
Bug: https://jira.iotivity.org/browse/IOT-1111
Cc: iotivity-dev@lists.iotivity.org
Cc: yocto@yoctoproject.org
Origin: https://github.com/tizenteam/meta-oic
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>