Update for IoTivity 1.1.1
* Inspired from Kishen Maloor's iotivity_1.1.0.bb.
* Note this version of recipe
  is using upstream's git repo as source
  because it's better for upstream/downstream cooperation
  More details at:
  https://wiki.iotivity.org/yocto
* Update to upstream "1.1-rel" maintenance branch
  - QA checks are fixed
    to support Yocto jethro base and later,
    without it packaging task will fail and report this message :
    ERROR: QA Issue: No GNU_HASH in the elf binary
* Tinycobor is updated to v0.2.1.
* Gtest is now statically linked.
* Security is still not enabled,
  but can be easly enabled with "SECURED=1" scons's flag.

Signed-off-by: Kishen Maloor <kishen.maloor@intel.com>