Update for IoTivity 1.1.1
* Inspired from Kishen Maloor's iotivity_1.1.0.bb.
* Note this version of recipe
  is using upstream's git repo as source
  because it's better for upstream/downstream cooperation
  More details at:
  https://wiki.iotivity.org/yocto
* Update to upstream "1.1-rel" maintenance branch
  - QA checks are fixed
    to support Yocto jethro base and later,
    without it packaging task will fail and report this message :
    ERROR: QA Issue: No GNU_HASH in the elf binary
* Tinycobor is updated to v0.2.1.
* Gtest is now statically linked.
* Security is still not enabled,
  but can be easly enabled with "SECURED=1" scons's flag.

Change-Id: Ib6f69c24434615d178ccef15cad96142e2b837aa
Bug: https://jira.iotivity.org/browse/IOT-1111
Cc: iotivity-dev@lists.iotivity.org
Cc: yocto@yoctoproject.org
Credit-to: Kishen Maloor <kishen.maloor@intel.com>
Origin: https://github.com/tizenteam/meta-oic
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>